version: 2
jobs:
  build:
    docker:
      - image: node:8.0
    steps:
      - checkout
      - run: |
          taskName=$CIRCLE_BRANCH
          if [[ -d $taskName ]]
          then
            node _validator/validator.js $taskName ALL
          fi
          
          #                                     _db_tasks
          
          taskName=_db_tasks/$CIRCLE_BRANCH
          if [[ -d $taskName ]]
          then
            node _validator/validator.js $taskName ALL
          fi
          
          #                                     _devops_tasks
          
          taskName=_devops_tasks/$CIRCLE_BRANCH
          if [[ -d $taskName ]]
          then
            node _validator/validator.js $taskName ALL
          fi
