version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: |
          validate() {
            cd _validator
            node validator.js $1 ALL
            cd ..
          }
          cd _validator
          npm install
          cd ..
          taskName=$CIRCLE_BRANCH
          if [[ -d $taskName ]]
          then
            validate $taskName
          fi
          
          #                                     _db_tasks
          
          taskName=_db_tasks/$CIRCLE_BRANCH
          if [[ -d $taskName ]]
          then
            validate $taskName
          fi
          
          #                                     _devops_tasks
          
          taskName=_devops_tasks/$CIRCLE_BRANCH
          if [[ -d $taskName ]]
          then
            validate $taskName
          fi
